version: '1'
services:

  frontend:
    image: airell/raffle-shopping-frontend:latest
    build:
      context: ../RaffleShopping-Frontend
    ports:
    - "3000:3000"
    environment:
    - REACT_APP_API_KEY=${REACT_APP_API_KEY}
    - REACT_APP_AUTH_DOMAIN=${REACT_APP_AUTH_DOMAIN}
    - REACT_APP_PROJECT_ID=${REACT_APP_PROJECT_ID}
    - REACT_APP_STORAGE_BUCKET=${REACT_APP_STORAGE_BUCKET}
    - REACT_APP_MESSAGING_SENDER_ID=${REACT_APP_MESSAGING_SENDER_ID}
    - REACT_APP_APP_ID=${REACT_APP_APP_ID}
    - REACT_APP_MEASUREMENT_ID=${REACT_APP_MEASUREMENT_ID}
    networks:
    - raffle-network
    labels:
      kompose.service.type: LoadBalancer

  raffleshopping-services-customers-api:
    image: airell/raffle-shopping-customer-service:latest
    build:
      context: ./
      dockerfile: RaffleShopping.Services.Customers.Api/Dockerfile
    ports:
    - "50000:80"
    environment:
    - CONNECTION_STRING=${CUSTOMERS_CONNECTION_STRING}
    - DATABASE_NAME=${CUSTOMERS_DATABASE_NAME}
    - COLLECTION_NAME=${CUSTOMERS_COLLECTION_NAME}
    networks:
    - raffle-network    
    labels:
      kompose.service.type: LoadBalancer

  raffleshopping-services-raffleevents-api:
    image: airell/raffle-shopping-raffle-event-service:latest
    build:
      context: ./
      dockerfile: RaffleShopping.Services.RaffleEvents.Api/Dockerfile
    ports:
    - "50001:80"
    networks:
    - raffle-network
    labels:
      kompose.service.type: LoadBalancer

  raffleshopping-services-catalogs-api:
    image: airell/raffle-shopping-catalog-service:latest
    build:
      context: ./
      dockerfile: RaffleShopping.Services.Catalogs.Api/Dockerfile
    ports:
    - "50002:80"
    environment:
    - CONNECTION_STRING=${CATALOGS_CONNECTION_STRING}
    - DATABASE_NAME=${CATALOGS_DATABASE_NAME}
    - COLLECTION_NAME=${CATALOGS_COLLECTION_NAME}
    networks:
    - raffle-network    
    labels:
      kompose.service.type: LoadBalancer

  raffleshopping-api-gateway:
    image: airell/raffle-shopping-api-gateway:latest
    build:
      context: ./
      dockerfile: RaffleShopping.ApiGateway/Dockerfile
    ports:
    - "5000:80"
    volumes:
    - ${PWD}/RaffleShopping.ApiGateway/ocelot:/app/ocelot
    networks:
    - raffle-network

networks:
 raffle-network:
   driver: bridge