version: '1'
services:
  raffleshopping.services.customers.api:
    image: airell/raffle-shopping-customer-service:latest
    build:
      context: ./
      dockerfile: RaffleShopping.Services.Customers.Api/Dockerfile
    ports:
    - "50000:80"

  raffleshopping.services.raffleevents.api:
    image: airell/raffle-shopping-raffle-event-service:latest
    build:
      context: ./
      dockerfile: RaffleShopping.Services.RaffleEvents.Api/Dockerfile
    ports:
    - "50001:80"
