version: '3.4'

services:
  raffleshopping.services.customers.api:
    image: ${DOCKER_REGISTRY-}raffleshoppingservicescustomersapi
    build:
      context: .
      dockerfile: RaffleShopping.Services.Customers.Api/Dockerfile
#    ports:
#    - "50002:80"

  raffleshopping.services.raffleevents.api:
    image: ${DOCKER_REGISTRY-}raffleshoppingservicesraffleeventsapi
    build:
      context: .
      dockerfile: RaffleShopping.Services.RaffleEvents.Api/Dockerfile
#    ports:
#    - "50000:80"
