version: '1'
services:
  frontend:
    image: airell/raffle-shopping-frontend:latest
    build:
      context: ../RaffleShopping-Frontend
    ports:
    - "3000:3000"
    labels:
      kompose.service.type: LoadBalancer


  raffleshopping-services-customers-api:
    image: airell/raffle-shopping-customer-service:latest
    build:
      context: ./
      dockerfile: RaffleShopping.Services.Customers.Api/Dockerfile
    ports:
    - "50000:80"
    environment:
    - CONNECTION_STRING=${CONNECTION_STRING}
    - DATABASE_NAME=${DATABASE_NAME}
    - COLLECTION_NAME=${COLLECTION_NAME}
    labels:
      kompose.service.type: LoadBalancer


  raffleshopping-services-raffleevents-api:
    image: airell/raffle-shopping-raffle-event-service:latest
    build:
      context: ./
      dockerfile: RaffleShopping.Services.RaffleEvents.Api/Dockerfile
    ports:
    - "50001:80"
    labels:
      kompose.service.type: LoadBalancer
