apiVersion: v1
kind: Secret
metadata:
  name: catalogs-secret
type: Opaque
data: 
  CONNECTION_STRING: bW9uZ29kYjovL2NhdGFsb2dzLWRiLXJhZmZsZS1zaG9wcGluZzp6RWUwVkhOanhJTENXeVRDODd5Z29sSklXUUdMYXNFQmFpc2d3ZkJSTG5PZWxONTVBd3NVa0toVHE5QWlPRDZZTW9CQjBXVVVRd3ZsQUNEYkZROWR1Zz09QGNhdGFsb2dzLWRiLXJhZmZsZS1zaG9wcGluZy5tb25nby5jb3Ntb3MuYXp1cmUuY29tOjEwMjU1Lz9zc2w9dHJ1ZSZyZXBsaWNhU2V0PWdsb2JhbGRiJnJldHJ5d3JpdGVzPWZhbHNlJm1heElkbGVUaW1lTVM9MTIwMDAwJmFwcE5hbWU9QGNhdGFsb2dzLWRiLXJhZmZsZS1zaG9wcGluZ0A=
  DATABASE_NAME: Y2F0YWxvZ3MtZGI=
  COLLECTION_NAME: Y2F0YWxvZ3M=
  SERVICE_BUS_CONNECTION_STRING: RW5kcG9pbnQ9c2I6Ly9yYWZmbGVzaG9wcGluZy5zZXJ2aWNlYnVzLndpbmRvd3MubmV0LztTaGFyZWRBY2Nlc3NLZXlOYW1lPU1hbmFnZTtTaGFyZWRBY2Nlc3NLZXk9R0tRS3MrUGM5M3hVcGtxa0ZGckdzM092TzZQUnFVZTE5K0FTYkFhZWVQVT07RW50aXR5UGF0aD1jYXRhbG9ncw==
  SERVICE_BUS_QUEUE_NAME: Y2F0YWxvZ3M=
  BLOB_STORAGE_CONNECTION_STRING: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPXJhZmZsZXNob3BwaW5nYmxvYjtBY2NvdW50S2V5PWZlSVhrbmhHOVRaL2ZRLzJhWU15Ti9qVmhBaDJneklRb3BqbmVQaEUvd2dIeFFpbDhhWFB4Z0Jya3lXMXU1UXpDUjNPbVNGbUlIWmkrQVN0dndqOGR3PT07RW5kcG9pbnRTdWZmaXg9Y29yZS53aW5kb3dzLm5ldA==
  BLOB_STORAGE_CONTAINER_NAME: Y2F0YWxvZy1pbWFnZXM=
  BLOB_STORAGE_ACCOUNT_NAME: cmFmZmxlc2hvcHBpbmdibG9i