apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: raffleshopping-services-catalogs-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: raffleshopping-services-catalogs-api
  minReplicas: 1
  maxReplicas: 15
  targetCPUUtilizationPercentage: 50