apiVersion: v1
kind: Secret
metadata:
  name: secret-keys
type: Opaque
data: 
  CONNECTION_STRING: bW9uZ29kYjovL2N1c3RvbWVycy1kYi1yYWZmbGUtc2hvcHBpbmc6dUdhblhOTEJieTJlZ2c4YmJRRVpIUlRTZVZXQmNpYmVtZ0hEUXI1cThFcGFBYVNYR0hibHZxUWRCRDlxY1VMVWE5M0xraiROR0xmSmp4RDJJT0FDZGJPdnNyczE9PTphd2FycmVsbC1yYWZmbGUtc2hvcHBpbmcubW9uZ28uY29tcG9zLmF6dXJlLmNvbToxMDI1NTU6L3NzbD10cnVlJ3w/c3NsPXRydWUmdHJlbnw9dHJ1ZidvcHBhcmtpdHM9QGN1c3RvbWVycy1kYi1yYWZmbGUtc2hvcHBpbmc6LzEwMjU1NT9zc2w9dHJ1ZScmcmVwaWxpYXRpb249Z2xvYmFsZGI=
  DATABASE_NAME: Y3VzdG9tZXJzLWRi
  COLLECTION_NAME: Y3VzdG9tZXJz