name: Raffle Shopping API CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Create env file
      run: |
        echo "${{ secrets.ENV_SECRET }}" | base64 --decode > .env

  CustomerTest:
    name: CustomerTest
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      working-directory: RaffleShopping.Services.Customers.UnitTests
      run: |
        dotnet restore
    - name: CustomerBuild
      working-directory: RaffleShopping.Services.Customers.UnitTests
      run: |
        dotnet build --no-restore

    - name: Run Tests
      working-directory: RaffleShopping.Services.Customers.UnitTests
      run: |
        dotnet test --no-build --verbosity normal
